### ISSUE TITLE
17计科3班-黄燕惟

### ISSUE THREAD

**Issue by Huangyanwei** [huashangxueyuan/hackathon_round_2#13]
慢慢的越来越了解html和css了，可以说是收获了很多啊，感觉找到自己喜欢的东西，会更加努力学习的！！
这是第二次任务的代码：https://github.com/Huangyanwei/douyin

**Comment by Candiceljy** [comment]
perfect ! 通过站点二考核。 继续加油，把喜欢的事情学好，甚至可以成为一名优秀程序员！
