### ISSUE TITLE
17计科国际班纪秋怡

### ISSUE THREAD

**Issue by DonelyOrJune** [huashangxueyuan/hackathon_round_2#20]
抖音html：https://github.com/DonelyOrJune/SecondText/blob/master/douyindemo.html
抖音css：https://github.com/DonelyOrJune/SecondText/blob/master/douyindemo.css
学习心得：https://github.com/DonelyOrJune/SecondText/blob/master/README.md

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
评优啦~
