### ISSUE TITLE
18 信工计科 徐燊亮

### ISSUE THREAD

**Issue by xushenl** [huashangxueyuan/hackathon_round_2#33]
赶在deadline来交啦！
[这个网页的演示地址](https://kizunaaai.github.io/douyin/)
emm那个二维码放大的那个还没有想到怎么实现的所以用了放大来代替，效果一般
[这个是仓库的地址](https://github.com/kizunaaai/douyin)
由于对定位和布局还不是掌握的十分透彻，所以心得还在完善

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
