### ISSUE TITLE
15计科1-朱彬彬

### ISSUE THREAD

**Issue by enjoy-binbin** [huashangxueyuan/hackathon_round_2#4]
项目地址：
https://github.com/enjoy-binbin/TikTok

演示地址：
https://enjoy-binbin.github.io/TikTok/

心得放在README里了

**Comment by Candiceljy** [comment]
good~很优秀，能够保持不断学习的心态，并不断发现问题，分析问题，解决问题的好习惯真的很棒，继续加油，希望你能在比赛中获得好成绩，在前端和后端上都有巨大的收获。
