### ISSUE TITLE
18旅管 林彤欣

### ISSUE THREAD

**Issue by Reneeltx** [huashangxueyuan/hackathon_round_2#42]
https://github.com/huashangxueyuan/hackathon_round_2/issues

这是我的仓库地址，css有点不太理解，抖音主页有一些也不太对，希望能在周四的培训中理解一些，同时也很感谢帮助我的人！

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
