### ISSUE TITLE
17计科国际班冼丽铧

### ISSUE THREAD

**Issue by liva0** [huashangxueyuan/hackathon_round_2#50]
老师好,请审核!
这是心得: https://github.com/liva0/-2/blob/master/README.md
这是补全的html代码: https://github.com/liva0/-2/blob/master/index.html
这是补全的css抖音代码: https://github.com/liva0/-2/blob/master/index.css

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
