### ISSUE TITLE
17本市场营销3班 王恒

### ISSUE THREAD

**Issue by miedoso** [huashangxueyuan/hackathon_round_2#55]
搞了好久摸索了一个多星期回看了不知道多少遍才完成。。
我觉得主要是记忆力要花时间去记住那些代码的意思，而且其实老师已经给了我们很多的帮助比如文件和网址背景都做好了才让我们加入一些CSS的内容和加入文字和图片。
谢谢老师！！你们辛苦了。
https://github.com/miedoso/douyin

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！继续加油！
