### ISSUE TITLE
18-软件工程2班-李荣钊

### ISSUE THREAD

**Issue by Hrztly** [huashangxueyuan/hackathon_round_2#62]
链接地址：https://github.com/Hrztly/Hrztly.github.io/tree/master/%E6%8A%96%E9%9F%B3%E5%AE%98%E7%BD%91/douyin
演示地址：https://hrztly.github.io/%E6%8A%96%E9%9F%B3%E5%AE%98%E7%BD%91/douyin/
心路历程：由于还有一些地方还不是很懂，在摸索中前进，所以页面做得不是很好，但还会继续观看视频内容，加深理解，加油！谢谢老师！

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
