### ISSUE TITLE
18计科5班陈静

### ISSUE THREAD

**Issue by x1575887543** [huashangxueyuan/hackathon_round_2#64]
代码地址  https://github.com/x1575887543/x1575887543.github.com/tree/master/douyin
演示地址 https://x1575887543.github.io/douyin/
之前没想到round和exercise是分开的，求老师顺便也把round_1的我的任务也关闭了，谢谢，真的不好意思晚交了。

**Comment by Candiceljy** [comment]
good ！恭喜通过任务二考核！
期待你在终点站获得好成绩！
